### ISSUE TITLE
Crash when LocationMapViewer is opend with geo-uri from other app.

### ISSUE THREAD

**Issue by StickyDigit** [k3b/LocationMapViewer#18]
Tested on android 10 and 11 (LineageOS), using real and fake GPS. On the Android 11 I've tried on devices with and without Gapps.

When using 'view' action from 'Location Share' (ca.cmetcalfe.locationshare), at first run the app asks permission to access files, and brings up the "Location Map Viewer keeps stopping" dialogue.

Subsequent attempt just flash up the screen for Location Map Viewer, which immediately quits back to Location Share.

From "share to", e.g. "My Position" (net.mypapitmobile.myposition) Location Map Viewer does not appear in the list of targets.

The same happens from "GPSTest" (com.android.gpstests.osmdroid), both for share (absent), and view (crash) actions.

**Comment by StickyDigit** [comment]
FWIW, the android 10 is without Gapps.

**Comment by k3b** [comment]
The problem is reproducable with https://f-droid.org/wiki/page/ca.cmetcalfe.locationshare

2021-06-30 22:58:02.168 23301-23301/de.k3b.android.locationMapViewer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.k3b.android.locationMapViewer, PID: 23301
    java.lang.RuntimeException: Unable to start activity ComponentInfo{de.k3b.android.locationMapViewer/de.k3b.android.locationMapViewer.LocationMapViewer}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3323)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7615)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at java.net.URLDecoder.decode(URLDecoder.java:137)
        at de.k3b.android.geo.AndroidGeoLoadService.getName(AndroidGeoLoadService.java:124)
        at de.k3b.android.locationMapViewer.LocationMapViewer.openGeoFileFromIntent(LocationMapViewer.java:932)
        at de.k3b.android.locationMapViewer.LocationMapViewer.onCreateEx(LocationMapViewer.java:271)
        at de.k3b.android.widgets.FilePermissionActivity.checkPermissions(FilePermissionActivity.java:105)
        at de.k3b.android.widgets.FilePermissionActivity.onCreate(FilePermissionActivity.java:120)
        at de.k3b.android.locationMapViewer.LocationMapViewer.onCreate(LocationMapViewer.java:185)
        at android.app.Activity.performCreate(Activity.java:7835)
        at android.app.Activity.performCreate(Activity.java:7824)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3298)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7615) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 
2021-06-30 22:58:02.197 23301-23301/de.k3b.android.locationMapViewer I/Process: Sending signal. PID: 23301 SIG: 9

**Comment by k3b** [comment]
bugfix in next f-droid release v0.3.8.210702

**Comment by StickyDigit** [comment]
Waiting for F-Droid builds is like waiting for paint to dry, only slower. I just built this with Studio.

It now works as target for "Open with" from GPSTest, and does not crash. However, it is still not in the apps listed when using 'share', from e.g. GPSTest.

**Comment by StickyDigit** [comment]
(same for Locattion Share app)

**Comment by k3b** [comment]
Thanks for your feedback


if you install https://github.com/k3b/intent-intercept on you android then you can see which intent is uses in the share or view 

i.e. https://f-droid.org/wiki/page/ca.cmetcalfe.locationshare implements share as SEND with mime "text/plain"

I have decided that locationmapviewer will not catch every 'SEND with mime "text/plain"' because i see it as SPAM if only 0.01% of all "text/plain" messages contain a geo-iformation that can be processed by locationmapviewer.

As a workaround you can install https://f-droid.org/en/packages/com.tasomaniac.openwith.floss/ that catches  mime "text/plain"', analyses it and translates it back to a "geo" uri.

**Comment by StickyDigit** [comment]
You're quite right about the mime type of course. GPSTest also spits out a geo: URI as text/plain via share, which is great if you want to send a text or paste it into a note, but not so great if you want to feed it to a navigation/mapping app.

The list of apps that offer to grok the shared text/plain geo: is huge on my phone, with even VLC and NewPipe offering to have a go. Strangely absent (from this users' perpective) are almost all the navigation apps (OSMin and LocationMapViewer  etc.), so you are certainly following the fashion by ignoring text/plain as a nav app. Maybe you could start a trend by attempting to parse text/plain, and issue an error/quit if not /^geo:/. Sharing the link at VLC, gets a simple message "the location geo:0.00,0.00 cannot be played".

Firing the share through OpenWith, then Intent Intercept, it looks like it's turning it into a geo uri of sorts, but LMV is not in the list of receivers, only web browsers (and intent-intercept).

On the plus side, this app now serves as a rare receiver for 'VIEW' of geo: A feature lacking in almost all map apps. :-D

**Comment by StickyDigit** [comment]
Seems Intent Intercept share function is a bit broken, I ended up sharing to myself by email as most of the other methods (barcode scanner, editor) didn't get any data. Copy to clipboard works OK too. Should I post a bug on Intent Intercept? (An excellent tool by the way.. nice one!)

Here's what I get from Location Share, via OpenWith. I've redacted the list of browsers here, it is literally only all my web browsers.

```
intent://geo:50.00000,-1.00000#Intent;scheme=https;launchFlags=0x13080000;S.android.intent.extra.TEXT=geo%3A50.00000%2C-1.00000;end 
------------ 
ACTION: android.intent.action.VIEW 
DATA: https://geo:50.00000,-1.00000 
URI: intent://geo:50.00000,-1.00000#Intent;scheme=https;launchFlags=0x13080000;S.android.intent.extra.TEXT=geo%3A50.00000%2C-1.00000;end 
FLAGS: 
FLAG_RECEIVER_FOREGROUND 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 
FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET 
EXTRAS: 
1 Class: java.lang.String 
Key: android.intent.extra.TEXT 
Value: geo:50.00000,-1.00000
2 EXTRAS: 
Error extracting Extras 

------------ 
MATCHING ACTIVITIES: 
..All my browsers and nothing else.
```

**Comment by k3b** [comment]
If you know other geo aware apps feel free to add them to https://github.com/k3b/k3b-geoHelper/wiki/Android-Geo-aware-apps . i will add the apps mentioned in this thread

* https://github.com/pR0Ps/LocationShare
* https://github.com/tasomaniac/OpenLinkWith

**Comment by StickyDigit** [comment]
Rather than risk slotting these into the wrong category, (and as I can't see an obvious way to edit the Wiki directly), I'll drop a few here.

These are available at  [IzzyOnDroid F-Droid repo](https://apt.izzysoft.de/fdroid)

[Mock my GPS](https://github.com/warren-bank/Android-Mock-Location)
A mock GPS provider with bookmarks and a trip simulator.

[OSMin](https://github.com/janbar/osmin)
A navigation app with offline maps.

These are from [F-Droid](f-droid.org)

[GMaps WV](https://gitlab.com/divested-mobile/maps) 
A restricted WebView wrapper for accessing the web version of Google Maps.

[My Position](https://github.com/gjedeer/mylocation)
Location sharing app with multiple output formats.

[GPSTest](https://github.com/barbeau/gpstest)
A fairly comprehensive GPS toolkit.

[StreetComplete](https://github.com/streetcomplete/StreetComplete)
A very user friendly way to contribute to OpenStreetMap.

[Vespucchi](https://github.com/MarcusWolschon/osmeditor4android)
A very comprehensive OpenStreetMap editor.

[Trail Sense](https://github.com/kylecorry31/Trail-Sense)
Use your phone's sensors to assist with wilderness treks or survival situations.
Can receive 'view' intent to lay down a beacon in the app.

**Comment by k3b** [comment]
Thanks a lot :-) . I have appended your list to  https://github.com/k3b/k3b-geoHelper/wiki/Android-Geo-aware-apps .
